(module
  (import "rustfrp" "subscribe_event" (func $subscribe (param i32 i32) (result i32)))
  (import "rustfrp" "control_process" (func $control (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $heap (mut i32) (i32.const 4096))
  (data (i32.const 0) "connection.disconnectedfailoverdefault")
  (func (export "rustfrp_alloc") (param $len i32) (result i32)
    (local $ptr i32) (local.set $ptr (global.get $heap))
    (global.set $heap (i32.add (local.get $ptr) (local.get $len))) (local.get $ptr))
  (func (export "rustfrp_start") (result i32)
    (call $subscribe (i32.const 0) (i32.const 23)))
  (func (export "rustfrp_on_event") (param i32 i32) (result i32)
    (call $control (i32.const 23) (i32.const 8) (i32.const 31) (i32.const 7)))
  (func (export "rustfrp_stop") (result i32) (i32.const 0)))
