(module
  (import "rustfrp" "get_config" (func $config (param i32 i32 i32 i32) (result i32)))
  (import "rustfrp" "subscribe_event" (func $subscribe (param i32 i32) (result i32)))
  (import "rustfrp" "http_post" (func $post (param i32 i32 i32 i32) (result i32)))
  (memory (export "memory") 1)
  (global $heap (mut i32) (i32.const 8192))
  (data (i32.const 0) "webhook.urlconnection.disconnected")
  (func (export "rustfrp_alloc") (param $len i32) (result i32)
    (local $ptr i32) (local.set $ptr (global.get $heap))
    (global.set $heap (i32.add (local.get $ptr) (local.get $len))) (local.get $ptr))
  (func (export "rustfrp_start") (result i32)
    (call $subscribe (i32.const 11) (i32.const 23)))
  (func (export "rustfrp_on_event") (param $body i32) (param $body_len i32) (result i32)
    (local $url_len i32)
    (local.set $url_len (call $config (i32.const 0) (i32.const 11) (i32.const 1024) (i32.const 2048)))
    (if (result i32) (i32.gt_s (local.get $url_len) (i32.const 0))
      (then (call $post (i32.const 1024) (local.get $url_len) (local.get $body) (local.get $body_len)))
      (else (local.get $url_len))))
  (func (export "rustfrp_stop") (result i32) (i32.const 0)))
